spring:
  datasource:
    url: ${DB_URL}
    username: admin
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: WARN